import type {Metadata} from 'next';
import {Noto_Sans_KR} from 'next/font/google';
import './globals.css';
import {Providers} from './Provider';

const noto = Noto_Sans_KR({subsets: ['latin']});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='ko'>
			<body className={noto.className}>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
